services:
  smarthub-app:
    container_name: smarthub-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_PORT}:8088"
    volumes:
      - ./:/app
    environment:
      DB_DSN: ${DB_DSN}
    depends_on:
      - db
      - migrations
    restart: always

  db:
    container_name: smarthub-db
    image: postgres:17.4
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: smarthub-rabbitmq
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"  # AMQP
      - "15672:15672"  # Web UI
      - "1883:1883"  # MQTT
      - "8883:8883"  # MQTT over SSL
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    command: sh -c "rabbitmq-plugins enable rabbitmq_mqtt && rabbitmq-server"
    depends_on:
      - db
